{"name": " -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD66FD+812797]\n\tOrdinal0 [0x00CBDFFA+712698]\n\tOrdinal0 [0x00D2506B+1134699]\n\tOrdinal0 [0x00D3514A+1200458]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 26, in OpenPopupLogin\n    context.driver.find_element(By.XPATH, \"/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[3]/div[\"\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 857, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch chrome browser", "status": "passed", "start": 1667585624539, "stop": 1667585625601}, {"name": "When le site est lancé", "status": "passed", "start": 1667585625602, "stop": 1667585674611}, {"name": "Then Ouvrir le popup de connexion", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD66FD+812797]\n\tOrdinal0 [0x00CBDFFA+712698]\n\tOrdinal0 [0x00D2506B+1134699]\n\tOrdinal0 [0x00D3514A+1200458]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 26, in OpenPopupLogin\n    context.driver.find_element(By.XPATH, \"/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[3]/div[\"\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 857, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667585674611, "stop": 1667585674613}, {"name": "And Remplir les champs avec un email \"amin29\" et un mot de passe \"Amin29\"", "status": "skipped", "start": 1667585674614, "stop": 1667585674614}, {"name": "Then Clicker sur le boutton Se connecter", "status": "skipped", "start": 1667585674614, "stop": 1667585674614}, {"name": "Then User est connecté avec succès", "status": "skipped", "start": 1667585674614, "stop": 1667585674614}, {"name": "And Fermer le browser", "status": "skipped", "start": 1667585674614, "stop": 1667585674614}], "parameters": [{"name": "Email", "value": "amin29"}, {"name": "Password", "value": "Amin29"}], "start": 1667585624539, "stop": 1667585674614, "uuid": "a8b13ed5-12b4-44e6-a53d-0862d22db648", "historyId": "f23f8984e0bc0a67d4ae0fe2b91b1d1b", "fullName": "AA User i want to sign up: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "AA User i want to sign up"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}