{"name": " -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD65C0+812480]\n\tOrdinal0 [0x00CC992A+760106]\n\tOrdinal0 [0x00CC8313+754451]\n\tOrdinal0 [0x00CC861D+755229]\n\tOrdinal0 [0x00CD800E+819214]\n\tOrdinal0 [0x00D360CD+1204429]\n\tOrdinal0 [0x00D21A8C+1120908]\n\tOrdinal0 [0x00D359E2+1202658]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 21, in LancheWebSite\n    context.driver.get(\"BaseUrl\")\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch chrome browser", "status": "passed", "start": 1667583989886, "stop": 1667583990971}, {"name": "When le site est lancé", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00E31ED3+2236115]\n\tOrdinal0 [0x00DC92F1+1807089]\n\tOrdinal0 [0x00CD65C0+812480]\n\tOrdinal0 [0x00CC992A+760106]\n\tOrdinal0 [0x00CC8313+754451]\n\tOrdinal0 [0x00CC861D+755229]\n\tOrdinal0 [0x00CD800E+819214]\n\tOrdinal0 [0x00D360CD+1204429]\n\tOrdinal0 [0x00D21A8C+1120908]\n\tOrdinal0 [0x00D359E2+1202658]\n\tOrdinal0 [0x00D218A6+1120422]\n\tOrdinal0 [0x00CFA73D+960317]\n\tOrdinal0 [0x00CFB71F+964383]\n\tGetHandleVerifier [0x010DE7E2+2743074]\n\tGetHandleVerifier [0x010D08D4+2685972]\n\tGetHandleVerifier [0x00EC2BAA+532202]\n\tGetHandleVerifier [0x00EC1990+527568]\n\tOrdinal0 [0x00DD080C+1837068]\n\tOrdinal0 [0x00DD4CD8+1854680]\n\tOrdinal0 [0x00DD4DC5+1854917]\n\tOrdinal0 [0x00DDED64+1895780]\n\tBaseThreadInitThunk [0x77176739+25]\n\tRtlGetFullPathName_UEx [0x77AA8FD2+1218]\n\tRtlGetFullPathName_UEx [0x77AA8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Features\\steps\\SignUp_Steps.py\", line 21, in LancheWebSite\n    context.driver.get(\"BaseUrl\")\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667583990971, "stop": 1667583990977}, {"name": "Then Ouvrir le popup de connexion", "status": "skipped", "start": 1667583990977, "stop": 1667583990977}, {"name": "And Remplir les champs avec un email \"amin29\" et un mot de passe \"Amin29\"", "status": "skipped", "start": 1667583990977, "stop": 1667583990977}, {"name": "Then Clicker sur le boutton Se connecter", "status": "skipped", "start": 1667583990977, "stop": 1667583990977}, {"name": "Then User est connecté avec succès", "status": "skipped", "start": 1667583990977, "stop": 1667583990977}, {"name": "And Fermer le browser", "status": "skipped", "start": 1667583990977, "stop": 1667583990977}], "parameters": [{"name": "Email", "value": "amin29"}, {"name": "Password", "value": "Amin29"}], "start": 1667583989885, "stop": 1667583990977, "uuid": "3e78122e-e7e1-42f3-bb76-e9ab61ca291b", "historyId": "f23f8984e0bc0a67d4ae0fe2b91b1d1b", "fullName": "AA User i want to sign up: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "AA User i want to sign up"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}